variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureRmWebAppDeployment@4
  inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(33471032-2c6d-497e-ae43-6659f54956af)'
        appType: 'webApp'
        WebAppName: 'webcalculator-app'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'