variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureRmWebAppDeployment@4
  inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Mysubscription'
        appType: 'webApp'
        WebAppName: 'vk-myapp1'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'